/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Kintia Ankuash
 */
public class PanelProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelProveedor
     */
    public PanelProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelNuevoCliente = new javax.swing.JPanel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        nomcuent = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        titular = new javax.swing.JTextField();
        nombanc = new javax.swing.JTextField();
        TxtNombre3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        TxtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(874, 450));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Administrar Proveedor");

        jPanelNuevoCliente.setBackground(new java.awt.Color(255, 0, 102));
        jPanelNuevoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanelNuevoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelNuevoCliente.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cédula/Ruc:");
        jPanelNuevoCliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 76, -1));
        jPanelNuevoCliente.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 180, -1));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelNuevoCliente.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Empresa:");
        jPanelNuevoCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 31, 110, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Responsable:");
        jPanelNuevoCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dirección:");
        jPanelNuevoCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 76, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Titular de la Cuenta:");
        jPanelNuevoCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));
        jPanelNuevoCliente.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 181, -1));
        jPanelNuevoCliente.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 193, 20));
        jPanelNuevoCliente.add(nomcuent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 193, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado:");
        jPanelNuevoCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 60, -1));

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Debaja" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanelNuevoCliente.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 24, 60, 20));

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanelNuevoCliente.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono:");
        jPanelNuevoCliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 62, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero de  Cuenta");
        jPanelNuevoCliente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 120, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre del Banco:");
        jPanelNuevoCliente.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Datos de la Cuenta");
        jPanelNuevoCliente.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, -1));
        jPanelNuevoCliente.add(titular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 193, -1));
        jPanelNuevoCliente.add(nombanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 193, -1));
        jPanelNuevoCliente.add(TxtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 193, 20));

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Buscar Por:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 76, -1));

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Nombres", "Apellidos" }));
        jPanel2.add(jComboBoxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyTyped(evt);
            }
        });
        jPanel2.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 224, -1));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelNuevoCliente.getAccessibleContext().setAccessibleName("Nuevo Proveedor");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        //        Cliente objeto_cliente = new Cliente();
        //        objeto_cliente.setNombre_cliente(TxtNombre.getText());
        //        objeto_cliente.setApellido_cliente(TxtApellido.getText());
        //        objeto_cliente.setCedula_cliente(TxtCedula.getText());
        //        objeto_cliente.setDireccion_cliente(TxtDireccion.getText());
        //        objeto_cliente.setTelefono_cliente(TxtTelefono.getText());
        //        objeto_cliente.setEmail_cliente(TxtEmail.getText());
        //        objeto_cliente.setEstado_cliente((String)jComboBoxEstado.getSelectedItem());
        //        escribirFichero(objeto_cliente);
        //        JOptionPane.showMessageDialog(null, "su cliente se guardo con exito");
        //        limpiarCampos();
        //        cargarTabla();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        //        try {
            //            List<Cliente> lista = this.modelo.getLista();
            //            lista.remove(this.jTableCliente.getSelectedRow());
            //            Cliente u = new Cliente();
            //            u.setNombre_cliente(TxtNombre.getText());
            //            u.setApellido_cliente(TxtApellido.getText());
            //            u.setCedula_cliente(TxtCedula.getText());
            //            u.setDireccion_cliente(TxtDireccion.getText());
            //            u.setTelefono_cliente(TxtTelefono.getText());
            //            u.setEmail_cliente(TxtEmail.getText());
            //            u.setEstado_cliente((String)jComboBoxEstado.getSelectedItem());
            //            lista.add(u);
            //            borrardatosfichero();
            //            for (int i = 0; i < lista.size(); i++) {
                //                escribirFichero(lista.get(i));
                //            }
            //            JOptionPane.showMessageDialog(null, "Su Usuario se Modifico Correctamente");
            //            limpiarCampos();
            //            cargarTabla();
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, "Debe selecionar una fila");
            //        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void TxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyTyped
        // TODO add your handling code here:
        //        TxtBuscar.addKeyListener(new KeyAdapter() {
            //            public void  keyReleased(final KeyEvent e){
                //                String cadena = (TxtBuscar.getText());
                //                repaint();
                //                filtro();
                //            }
            //        });
    //        trsFiltro = new TableRowSorter(jTableCliente.getModel());
    //        jTableCliente.setRowSorter(trsFiltro);
    }//GEN-LAST:event_TxtBuscarKeyTyped

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        // TODO add your handling code here:
        //        String ced = jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 2).toString();
        //        Cliente user = new LeerArchivos().obtenerCliente(ced);
        //        if (user != null) {
            //            TxtNombre.setText(user.getNombre_cliente());
            //            TxtApellido.setText(user.getApellido_cliente());
            //            TxtCedula.setText(user.getCedula_cliente());
            //            TxtDireccion.setText(user.getDireccion_cliente());
            //            TxtTelefono.setText(user.getTelefono_cliente());
            //            TxtEmail.setText(user.getEmail_cliente());
            //        }
    }//GEN-LAST:event_jTableClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombre3;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelNuevoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField nombanc;
    private javax.swing.JTextField nomcuent;
    private javax.swing.JTextField titular;
    // End of variables declaration//GEN-END:variables
}
