/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author Kintia Ankuash
 */
public class Principal extends javax.swing.JDialog {

    /**
     * Creates new form Principal
     */
    public Principal(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
//        this.setVisible(true);
//        this.setLocationRelativeTo(this);
//        this.inicio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu1 = new javax.swing.JButton();
        panl = new javax.swing.JPanel();
        inicio = new rsbuttom.RSButtonMetro();
        usurio = new rsbuttom.RSButtonMetro();
        clientes = new rsbuttom.RSButtonMetro();
        proveedor = new rsbuttom.RSButtonMetro();
        producto = new rsbuttom.RSButtonMetro();
        venta = new rsbuttom.RSButtonMetro();
        compra = new rsbuttom.RSButtonMetro();
        factura = new rsbuttom.RSButtonMetro();
        abono = new rsbuttom.RSButtonMetro();
        reporte = new rsbuttom.RSButtonMetro();
        principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu1.setBackground(new java.awt.Color(255, 0, 102));
        menu1.setForeground(new java.awt.Color(0, 0, 0));
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        menu1.setToolTipText("");
        menu1.setBorder(null);
        menu1.setBorderPainted(false);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel2.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        panl.setBackground(new java.awt.Color(255, 0, 102));
        panl.setForeground(new java.awt.Color(0, 0, 0));
        panl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setBackground(new java.awt.Color(255, 0, 102));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        inicio.setText("Inicio");
        inicio.setColorHover(new java.awt.Color(51, 51, 51));
        inicio.setColorNormal(new java.awt.Color(255, 0, 102));
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicio.setIconTextGap(25);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        panl.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        usurio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        usurio.setText("Usuarios");
        usurio.setColorHover(new java.awt.Color(51, 51, 51));
        usurio.setColorNormal(new java.awt.Color(0, 0, 0));
        usurio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usurio.setIconTextGap(25);
        usurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usurioActionPerformed(evt);
            }
        });
        panl.add(usurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        clientes.setBackground(new java.awt.Color(255, 0, 102));
        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        clientes.setText("Clientes");
        clientes.setColorHover(new java.awt.Color(51, 51, 51));
        clientes.setColorNormal(new java.awt.Color(255, 0, 102));
        clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientes.setIconTextGap(25);
        panl.add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        proveedor.setBackground(new java.awt.Color(255, 0, 102));
        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        proveedor.setText("Proveedor");
        proveedor.setColorHover(new java.awt.Color(51, 51, 51));
        proveedor.setColorNormal(new java.awt.Color(255, 0, 102));
        proveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        proveedor.setIconTextGap(25);
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });
        panl.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 40));

        producto.setBackground(new java.awt.Color(255, 0, 102));
        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        producto.setText("Producto");
        producto.setColorHover(new java.awt.Color(51, 51, 51));
        producto.setColorNormal(new java.awt.Color(255, 0, 102));
        producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        producto.setIconTextGap(25);
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        panl.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        venta.setBackground(new java.awt.Color(255, 0, 102));
        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        venta.setText("Venta");
        venta.setColorHover(new java.awt.Color(51, 51, 51));
        venta.setColorNormal(new java.awt.Color(255, 0, 102));
        venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        venta.setIconTextGap(25);
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        panl.add(venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 44));

        compra.setBackground(new java.awt.Color(255, 0, 102));
        compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        compra.setText("Compra");
        compra.setColorHover(new java.awt.Color(51, 51, 51));
        compra.setColorNormal(new java.awt.Color(255, 0, 102));
        compra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        compra.setIconTextGap(25);
        panl.add(compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 40));

        factura.setBackground(new java.awt.Color(255, 0, 102));
        factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        factura.setText("Factura");
        factura.setColorHover(new java.awt.Color(51, 51, 51));
        factura.setColorNormal(new java.awt.Color(255, 0, 102));
        factura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factura.setIconTextGap(25);
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        panl.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        abono.setBackground(new java.awt.Color(255, 0, 102));
        abono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        abono.setText("Abonos");
        abono.setColorHover(new java.awt.Color(51, 51, 51));
        abono.setColorNormal(new java.awt.Color(255, 0, 102));
        abono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        abono.setIconTextGap(25);
        abono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonoActionPerformed(evt);
            }
        });
        panl.add(abono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 40));

        reporte.setBackground(new java.awt.Color(255, 0, 102));
        reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        reporte.setText("Reportes");
        reporte.setColorHover(new java.awt.Color(51, 51, 51));
        reporte.setColorNormal(new java.awt.Color(255, 0, 102));
        reporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reporte.setIconTextGap(25);
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });
        panl.add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 40));

        jPanel1.add(panl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 450));

        principal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        int posicion = this.panl.getX();
        if (posicion >-1){
            Animacion.Animacion.mover_izquierda(0, -188, 2,2, panl);
        } else{
            Animacion.Animacion.mover_derecha(-188,0, 2,2, panl);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturaActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoActionPerformed

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reporteActionPerformed

    private void usurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usurioActionPerformed

    private void abonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abonoActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal dialog = new Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro abono;
    private rsbuttom.RSButtonMetro clientes;
    private rsbuttom.RSButtonMetro compra;
    private rsbuttom.RSButtonMetro factura;
    private rsbuttom.RSButtonMetro inicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu1;
    private javax.swing.JPanel panl;
    private javax.swing.JPanel principal;
    private rsbuttom.RSButtonMetro producto;
    private rsbuttom.RSButtonMetro proveedor;
    private rsbuttom.RSButtonMetro reporte;
    private rsbuttom.RSButtonMetro usurio;
    private rsbuttom.RSButtonMetro venta;
    // End of variables declaration//GEN-END:variables
}
