/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import org.edisoncor.gui.panel.PanelCurves;

/**
 *
 * @author Kintia Ankuash
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(this);
//        this.inicio.setSelected(true);
//        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divisor = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        inicio = new rsbuttom.RSButtonMetro();
        usurio = new rsbuttom.RSButtonMetro();
        clientes = new rsbuttom.RSButtonMetro();
        proveedor = new rsbuttom.RSButtonMetro();
        producto = new rsbuttom.RSButtonMetro();
        venta = new rsbuttom.RSButtonMetro();
        compra = new rsbuttom.RSButtonMetro();
        factura = new rsbuttom.RSButtonMetro();
        abono = new rsbuttom.RSButtonMetro();
        reporte = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(140, 200));

        divisor.setDividerLocation(200);
        divisor.setDividerSize(1);
        divisor.setMinimumSize(new java.awt.Dimension(180, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(874, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        inicio.setText("Inicio");
        inicio.setColorHover(new java.awt.Color(255, 0, 102));
        inicio.setColorNormal(new java.awt.Color(0, 0, 0));
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicio.setIconTextGap(25);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        usurio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        usurio.setText("Usuarios");
        usurio.setColorHover(new java.awt.Color(255, 0, 102));
        usurio.setColorNormal(new java.awt.Color(0, 0, 0));
        usurio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usurio.setIconTextGap(25);
        usurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usurioActionPerformed(evt);
            }
        });
        jPanel1.add(usurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 40));

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        clientes.setText("Clientes");
        clientes.setColorHover(new java.awt.Color(255, 0, 102));
        clientes.setColorNormal(new java.awt.Color(0, 0, 0));
        clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientes.setIconTextGap(25);
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        jPanel1.add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        proveedor.setText("Proveedor");
        proveedor.setColorHover(new java.awt.Color(255, 0, 102));
        proveedor.setColorNormal(new java.awt.Color(0, 0, 0));
        proveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        proveedor.setIconTextGap(25);
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });
        jPanel1.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 40));

        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        producto.setText("Producto");
        producto.setColorHover(new java.awt.Color(255, 0, 102));
        producto.setColorNormal(new java.awt.Color(0, 0, 0));
        producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        producto.setIconTextGap(25);
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        jPanel1.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        venta.setText("Venta");
        venta.setColorHover(new java.awt.Color(255, 0, 102));
        venta.setColorNormal(new java.awt.Color(0, 0, 0));
        venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        venta.setIconTextGap(25);
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        jPanel1.add(venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 44));

        compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        compra.setText("Compra");
        compra.setColorHover(new java.awt.Color(255, 0, 102));
        compra.setColorNormal(new java.awt.Color(0, 0, 0));
        compra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        compra.setIconTextGap(25);
        compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraActionPerformed(evt);
            }
        });
        jPanel1.add(compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 40));

        factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        factura.setText("Factura");
        factura.setColorHover(new java.awt.Color(255, 0, 102));
        factura.setColorNormal(new java.awt.Color(0, 0, 0));
        factura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factura.setIconTextGap(25);
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        jPanel1.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        abono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        abono.setText("Abonos");
        abono.setColorHover(new java.awt.Color(255, 0, 102));
        abono.setColorNormal(new java.awt.Color(0, 0, 0));
        abono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        abono.setIconTextGap(25);
        abono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonoActionPerformed(evt);
            }
        });
        jPanel1.add(abono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 40));

        reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        reporte.setText("Reportes");
        reporte.setColorHover(new java.awt.Color(255, 0, 102));
        reporte.setColorNormal(new java.awt.Color(0, 0, 0));
        reporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reporte.setIconTextGap(25);
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });
        jPanel1.add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 40));

        divisor.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(874, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/centrotato2.jpg"))); // NOI18N

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        divisor.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        this.divisor.setRightComponent(new Portada());
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    private void usurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usurioActionPerformed
        this.divisor.setRightComponent(new PanelUsuario());
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_usurioActionPerformed

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        this.divisor.setRightComponent(new PanelProveedor());
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
    this.divisor.setRightComponent(new PanelProducto());
        this.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_productoActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
       this.divisor.setRightComponent(new PanelVenta());
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturaActionPerformed

    private void abonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abonoActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reporteActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
    this.divisor.setRightComponent(new PanelCliente());
        this.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    private void compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraActionPerformed
        this.divisor.setRightComponent(new PanelCompra());
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_compraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaPrincipal dialog = new VistaPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro abono;
    private rsbuttom.RSButtonMetro clientes;
    private rsbuttom.RSButtonMetro compra;
    private javax.swing.JSplitPane divisor;
    private rsbuttom.RSButtonMetro factura;
    private rsbuttom.RSButtonMetro inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private rsbuttom.RSButtonMetro producto;
    private rsbuttom.RSButtonMetro proveedor;
    private rsbuttom.RSButtonMetro reporte;
    private rsbuttom.RSButtonMetro usurio;
    private rsbuttom.RSButtonMetro venta;
    // End of variables declaration//GEN-END:variables
}
